const Temp = () => {
    console.log("Temp component rendered");
    return (
        <>
            <p>Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.Das Überlappen der Komponenten Header und Temp kann daran liegen, dass im CSS keine Positionierung oder kein Abstand definiert ist. Standardmäßig haben Elemente die Position static, und ohne zusätzliche Styles können sie sich überlappen, wenn z. B. negative Margins, absolute Positionierung oder fehlende Höhenangaben verwendet werden.dfha</p>
        </>

    )
}
export default Temp